apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: warm-island
spec:
  displayName: WarmIsland 暖屿
  author:
    name: 暖心向阳335
    website: https://nxxy335.top/
  description: 具有独特气质的生活博客主题
  logo: /themes/warm-island/assets/logo.png
  homepage: https://nxxy335.top/
  repo: https://github.com/nxxy335top/halo-theme-WarmIsland
  issues: https://github.com/nxxy335top/halo-theme-WarmIsland/issues
  settingName: "warm-island-setting"
  configMapName: "warm-island-configMap"
  customTemplates:
    page:
      - name: MessageBoard
        description: 留言板
        screenshot:
        file: page_messageboard.html
  version: "1.0.0"
  requires: ">=2.24.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
