apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: warm-island
spec:
  displayName: WarmIsland 暖屿
  author:
    name: 暖心向阳335
    website: https://nxxy335.top/
  description: 暖如灯火，静如留白。暖屿以柔和的色调和舒缓的节奏回归内容本身，为记录与阅读留出一方安静从容的角落。
  logo: /themes/warm-island/assets/logo.png
  homepage: https://nxxy335.top/WarmIsland/
  repo: https://github.com/sunny-335/halo-theme-WarmIsland
  issues: https://github.com/sunny-335/halo-theme-WarmIsland/issues
  settingName: "warm-island-setting"
  configMapName: "warm-island-configMap"
  customTemplates:
    page:
      - name: MessageBoard
        description: 留言板
        screenshot:
        file: page_messageboard.html
  version: "0.1.0"
  requires: ">=2.24.0"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.en.html"
